# resolver: lts-9.0
# resolver: lts-9.6
# resolver: lts-11.0
# resolver: lts-11.3
# resolver: lts-11.5
resolver: lts-11.7
# resolver: nightly-2018-05-01

packages:
- '.'
# - core/
# - accelerate/

# extra-deps:
# - logging-effect-1.2.5
# - newtype-generics-0.5
#- matrix-market-attoparsec-0.1.0.5
# # - monad-log-0.1.1.0
# - accelerate-io-1.0.0.0
# - repa-3.4.1.3

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

ghc-options: {} 
  # "*" : -w -Wno-missing-signatures # -fprint-potential-instances
  # "*" : -Wno-missing-signatures -Wno-name-shadowing -Wno-unused-imports # -fprint-potential-instances
  
# Control whether we use the GHC we find on the path
# system-ghc: true
# 
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.1"
# 
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
# 
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
# 
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
